//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class historialCambios
    {
        public int numero { get; set; }
        public int numeroReclamo { get; set; }
        public System.DateTime fecha { get; set; }
        public string estado { get; set; }
    
        public virtual reclamo reclamo { get; set; }
    }
}
