//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class punto
    {
        public int numero { get; set; }
        public int numeroZona { get; set; }
        public decimal latitud { get; set; }
        public decimal longitud { get; set; }
    
        public virtual zona zona { get; set; }
    }
}
